version: "3"

services:
  hugo:
    container_name: hugo
    image: "peaceiris/hugo:v${HUGO_VERSION}"
    restart: always
    expose:
      - "80/tcp"
    volumes:
      - ${PWD}:/src
    command:
      - server
      - --bind=0.0.0.0
      - --port=80
      - --buildDrafts
      - --buildFuture
      - --baseURL=http://${LOCAL_DOMAIN}/
      - --appendPort=false
    networks:
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.default.protocol=http"
      - "traefik.backend=hugo"
      - "traefik.frontend.rule=Host:${LOCAL_DOMAIN}"
      - "traefik.port=80"

  traefik:
    image: bluerose/docker-traefik:1.0.1
    ports:
      - "${LOCAL_PORT}:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: on-failure
